
const mapping = {
  voie: "Voie",
  numero: "N°",
  nomPrenomOuDenomination: "Nom et prénom ou dénomination :",
  codePostal: "Code postal",
  commune: "Commune",
  telephone: "Téléphone",
  complement: "Complément",
  courriel2: "Courriel 2",
  codeActiviteEntrepriseNAF: "Code activité de l’entreprise (NAF) :",
  courriel1: "Courriel 1",
  effectifTotalSalariesEntreprise: "Effectif total salariés de l’entreprise :",
  typeEmployeur: "Type d’employeur",
  codeIDCCConventionCollective: "Code IDCC de la convention collective applicable :",
  employeurSpecifique: "Employeur spécifique",
  sexeF: "Sexe F",
  sexeM: "Sexe M",
  inscritListeSportifsHNNon: "Déclare être inscrit sur la liste des sportifs de haut niveau NON",
  inscritListeSportifsHNOui: "Déclare être inscrit sur la liste des sportifs de haut niveau OUI",
  travailleurHandicapeNon: "Déclare bénéficier de la reconnaissance travailleur handicapé NON",
  travailleurHandicapeOui: "Déclare bénéficier de la reconnaissance travailleur handicapé OUI",
  projetCreationRepriseEntrepriseOui: "Déclare avoir un projet de création ou de reprise d’entreprise OUI",
  projetCreationRepriseEntrepriseNon: "Déclare avoir un projet de création ou de reprise d’entreprise NON",
  numeroSIRET: "N°SIRET de l’établissement d’exécution du contrat :",
  nomNaissanceApprenti: "Nom de naissance de l’apprenti(e) :",
  nomUsage: "Nom d’usage",
  nirApprenti: "NIR de l’apprenti(e)",
  adresseApprentiNumero: "Adresse de l’apprenti(e) N°",
  adresseApprentiVoie: "Adresse de l’apprenti(e) Voie",
  adresseApprentiComplement: "Adresse de l’apprenti(e) Complément",
  adresseApprentiCP: "Adresse de l’apprenti(e) CP",
  adresseApprentiCommune: "Adresse de l’apprenti(e) Commune",
  adresseApprentiTelephone: "Adresse de l’apprenti(e) Téléphone",
  adresseApprentiCourriel1: "Adresse de l’apprenti(e) Courriel1",
  adresseApprentiCourriel2: "Adresse de l’apprenti(e) Courriel2",
  premierPrenomApprenti: "Le premier prénom de l’apprenti(e) selon l’état civil :",
  departementNaissanceApprenti: "Département naissance apprenti",
  nationaliteApprenti: "Nationalité apprenti",
  regimeSocialApprenti: "Régime social apprenti",
  situationAvantContrat: "Situation avant ce contrat",
  dernierDiplomePrepare: "Dernier diplôme ou titre préparé",
  communeNaissanceApprenti: "Commune naissance apprenti",
  intituleDiplomePrepare: "Intitulé précis du dernier diplôme ou titre préparé :",
  derniereClasseAnneeSuivie: "Dernière classe / année suivie",
  diplomePlusEleveObtenu: "Diplôme ou titre le plus élevé obtenu",
  representantLegalNomPrenom: "Représentant légal Nom / Prénom",
  maitreApprentissage2NomNaissance: "Maître d’apprentissage n° 2 Nom de naissance",
  maitreApprentissage1NomNaissance: "Maître d’apprentissage n°1 Nom de naissance",
  adresseRepresentantLegalCourriel1: "Adresse du représentant légal Courriel1",
  adresseRepresentantLegalCourriel2: "Adresse du représentant légal Courriel2",
  maitreApprentissage1Prenom: "Maître d’apprentissage n°1 Prénom",
  maitreApprentissage1Courriel1: "Maître d’apprentissage n°1 Courriel1",
  maitreApprentissage1Courriel2: "Maître d’apprentissage n°1 Courriel2",
  maitreApprentissage1Courriel2suite: "Maître d’apprentissage n°1 Courriel2suite",
  maitreApprentissage1EmploiOccupe: "Maître d’apprentissage n°1 Emploi occupé :",
  maitreApprentissage1DiplomePlusEleve: "Maître d’apprentissage n°1 Diplôme ou titre le plus élevé obtenu :",
  maitreApprentissage1NiveauDiplomePlusEleve: "Maître d’apprentissage n°1 Niveau de diplôme ou titre le plus élevé obtenu :",
  typeDerogation: "Type de dérogation :",
  dateDebutExecutionContrat: "Date de début d’exécution du contrat : _af_date",
  dateDebutFormationPratiqueEmployeur: "Date de début de formation pratique chez l’employeur : _af_date",
  maitreApprentissage1DateNaissance: "Maître d’apprentissage n°1 Date naissance_af_date",
  maitreApprentissage2DateNaissance: "Maître d’apprentissage n°2 Date naissance_af_date",
  apprentiDateNaissance: "Apprenti Date naissance_af_date",
  dateConclusion: "Date de conclusion : _af_date",
  dateEffetAvenant: "Si avenant, date d’effet :_af_date",
  dateFinContrat: "Date de fin du contrat ou de la période d’apprentissage_af_date",
  employeurAttestePieces: "L’employeur atteste disposer de l’ensemble des pièces justificatives nécessaires au dépôt du contrat",
  faitA: "Fait à",
  signatureEmployeur: "Signature de l’employeur",
  signatureApprenti: "Signature de l’apprenti(e)",
  dateFinEpreuvesExamens: "Date prévue de fin des épreuves ou examens :_af_date",
  dateDebutFormationCfa: "Date de début de formation en CFA :  _af_date",
  codeDiplome: "Code du diplôme",
  diplomeViseApprentiIntitulePrecise: "Diplôme ou titre visé par l’apprenti : Intitulé précis :",
  diplomeViseApprenti: "Diplôme ou titre visé par l’apprenti :",
  dureeFormation: "Durée de la formation :",
};

export default mapping;