// models/Cerfa.ts
import mongoose, { Schema, models, model } from 'mongoose';

const CerfaSchema = new Schema({
  NomApprenti: String,
  PrenomApprenti: String,
  NIR: String,
  Sexe: String,
  AppreDateNaissance: String,
  DepartementNaissance: String,
  CommunNaissance: String,
  Nationalite: String,
  RegimeSocial: String,
  EtatContrat: String,
  TypeContrat: String,
  DateDebutexe: String,
  DateConclusion: String,
  Salaire: Number,
  NomEntreprise: String,
  SIRET: String,
  AdresseNum: Number,
  AdresseVoie: String,
  CodePostal: Number,
  Commune: String,
  Telephone: String,
  Email1: String,
  Email2: String,
  TypeEmployeur: String,
  CodeNAF: Number,
  Effectif: Number,
  CodeIDCC: Number,
  EmployeurSpecifique: String,
  PrenomMaitre: String,
  NomMaitre: String,
  TéléphoneMaitre: String,
  Courriel1Maitre: String,
  Courriel2Maitre: String,
  DateNaissanceMaitre: String,
  EmploiOccupe: String,
  DiplomeTitre: String,
  NiveauDiplome: String,
}, { timestamps: true });

export const Cerfa = models.Cerfa || model('Cerfa', CerfaSchema);